# Generated by Django 4.0.5 on 2022-06-10 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_origin', models.CharField(max_length=100)),
                ('user_destination', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text_message', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
