# Generated by Django 4.0.5 on 2022-06-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_origin', models.CharField(max_length=100)),
                ('user_destination', models.CharField(max_length=100)),
                ('text_message', models.CharField(max_length=250)),
            ],
        ),
    ]
