# Generated by Django 4.0.5 on 2022-06-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0002_message_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['pub_date']},
        ),
    ]
