# Generated by Django 4.0.5 on 2022-06-10 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_avatar_description_avatar_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='website_url',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
